routes/web.php
<?php

use App\Faculty;
use App\Program;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*ruta para la pagina de inicio"*/
/*Route::get('/', function(){
	$user = Auth::user();

	return $user;
});*/


Route::resource('/facultades', 'facultiesController');
Route::resource('/programas', 'programsController');
Route::resource('/datos_personales', 'usersController');




Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{

	protected $fillable=[

    	"name",
    	"faculty_id",
    	"description"

    ];

    public function faculty(){

    	return $this->belongsTo("App\Faculty");

    }
    
}

app/Http/Controllers/programsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Program;
use App\Faculty;

class programsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        if (Auth::check()) {
            $programs = Program::all();
            $faculties = Faculty::all();

        return view("programs/program", compact('programs', 'faculties'));

        } else {
            return redirect("/");

        }
        
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return "404";
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*Recibe los datos del formulario en la ruta programas (archivo -> programs.blade.php) para crear datos en la tabla -> faculties*/ 
        $program = new Program;
        $program->name = $request->name;
        $program->faculty_id = $request->faculty_id;
        $program->description = $request->description;
        $program->save();

        return redirect('/programas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id){

        if (Auth::check()) {
            $program = Program::find($id);
            $faculties = Faculty::all();

        //vista 
            return view('programs/show', compact('program', 'faculties'));
        } else {
            return redirect("/");

        }
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $program = Program::find($id);

        $program->update($request->all());

        return redirect("/programas/{$id}");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $program = Program::find($id);

        $program->delete();

        return redirect("/programas"); 
    }
}

resources/views/programs/program.blade.php
@extends('layouts/layout')

@section('title', 'Programas') <!-- titulo de la de la pestaña -->

@section('content')


<!-- formulario para crear nuevos programas. Los datos se envían a la misma ruta y los toma la public function store del controllador (programsController) para crear nuevos registros en la tabla programs-->

<div class="container">
	<br>

@if(count($faculties) >= 1)
	<h3>Crear programas</h3>
	<form method="post" action= " {{route('programas.store')}}">
		{{csrf_field()}}
		<div class="mb-3">
			<input type="text" class="form-control"  name="name" placeholder ="Nombre..." required autofocus>
		</div>
		<select name="faculty_id">
			@foreach($faculties as $faculty)
			<option value="{{ $faculty->id }}">{{ $faculty->name }}</option>
			@endforeach
		</select>
		<div class="mb-3">
			<label for="description"  class="form-label" >Descripción</label>
			<textarea class="form-control" id="description" name="description"></textarea> 
		</div>
		<button type="submit" class="btn btn-primary" name="send">Crear</button>
	</form>

@else 
	<h3>Crea facultades para poder administrar programas<a class="link-light" href="{{route('facultades.index')}}"> ir</a></h3>
@endif


<br>

<!-- este foreach muestra los datos de la tabla faculties--> 	
	<table class="table table-striped table-responsive" >
		<thead class="thead-dark">
			<tr >
				<th scope="col">Nombre</th>
				<th scope="col">Descripción</th>
				<th>	</th>
			</tr>
		</thead>	
		<tbody>
			@foreach ($programs as $program)
			<tr>
				<td><a class="link-light" href="{{route('programas.show', $program->id)}}">{{$program->name}}</a></td>
				<td>{{$program->description}}</td>
				<td>

					 @if($student != '[]')
					 	Registrado

					 @else

					 	<form method="post" action= " {{route('datos_personales.store')}}">
						{{csrf_field()}}
						<div class="mb-3">
							<input type="hidden" name="program_id" value="{{$program->id}}">
						</div>
						<button type="submit" class="btn btn-success" name="send">Unirse</button>
					</form>

					 @endif

					

				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
</div>
	
	@endsection

resources/views/programs/show.blade.php
@extends('..layouts/layout')

@section('title', '') <!-- titulo de la de la pestaña -->

@section('content')



<!-- formulario para enviar datos actualizados de una facultad ya existente. Los datos se envían a la misma ruta y los toma la public function edit del controllador (facultiesController), para actualizar  registros en la tabla faculties-->


<!-- Boton para enviar el id de la facultad y eliminarla desde public function edit en el controllador (facultiesController), de la tabla faculties --> 


<div class="container justify-content-md-center">
	<br>

	<!-- Vista de la facultad -->
	<div >
		<h3>{{$program->name}}</h3>
		<p class="text-justify"> {{$program->description}} </p>
		<form method="post" action= "{{ route('programas.index')}}/{{$program->id}}" >
			{{csrf_field()}}
			<!-- Boton eliminar el registro de la tabla-->		
			<input type="hidden" name="_method" value="DELETE">

			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Editar</button>
			<button class="btn btn-secondary"  type="submit" name="send" value="Eliminar" >Eliminar</button>
		</form>
	</div>

	<br>

	<!-- Modal -->
	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">


			<div class="modal-content">
				<div class="modal-header">

					<h4 class="modal-title">Editar</h4>
				</div>
				<div class="modal-body">
					<div >
						<!-- formulario para enviar datos actualizados de un programa ya existente. Los datos se envían a la misma ruta y los toma la public function update del controllador (programsController), para actualizar  registros en la tabla programs-->
						<form method="post" action= "{{ route('programas.index')}}/{{$program->id}}">
							{{csrf_field()}}
							<input type="hidden" name="_method" value="PUT">
							<div class="mb-3"> 
								<input type="text" class="form-control"  name="name" value="{{$program->name}}" required autofocus>
							</div>
							<select name="faculty_id">
								@foreach($faculties as $faculty)
								<option value="{{ $faculty->id }}">{{ $faculty->name }}</option>
								@endforeach
							</select>
							<div class="mb-3"> 
								<textarea class="form-control" id="description" name="description" ></textarea> 
							</div>
							<button type="submit" class="btn btn-primary" name="send" value="Enviar">Aceptar</button>
						</form>


					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>

		</div>
	</div>



	<!-- Boton para enviar el id de la facultad y eliminarla desde public function edit en el controllador (facultiesController), de la tabla faculties --> 

</div>

@endsection