routes/web.php
<?php

use App\Faculty;
use App\Program;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*ruta para la pagina de inicio"*/
/*Route::get('/', function(){
	$user = Auth::user();

	return $user;
});*/


Route::resource('/facultades', 'facultiesController');
Route::resource('/programas', 'programsController');
Route::resource('/datos_personales', 'usersController');




Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Faculty.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
    
    protected $fillable=[
    	"name",
    	"description"

    ];

    public function program(){

    	return $this->hasOne("App\Program");

    }

    public function programs(){

        return $this->hasMany("App\Program");

    }


}

app/Http/Controllers/facultiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Faculty;
use App\Program;

class facultiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        if (Auth::check()) {

        //consulta con el modelo Faculty a la tabla faculties 
            $faculties = Faculty::all();

        //retorno de la vista junto con los datos de la consulta
            return view('faculties/faculty', compact('faculties')); 
        } else {
            return redirect("/");

        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return "404";
   }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {    
        /*Recibe los datos del formulario en la ruta facultades para crear datos en la tabla -> faculties*/ 
        $faculty = new Faculty;
        $faculty->name = $request->name;
        $faculty->description = $request->description;
        $faculty->save();

        return redirect("/facultades");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        /*Hace una consulta con la id que se proporciona en la ruta facultades/{id}*/
        $faculty =  Faculty::find($id);
        //return $programs =  Faculty::find($id)->programs;
        $programs =  Program::where('faculty_id', $id)->get();

        //vista 
        return view('faculties/show', compact('faculty', 'programs'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $faculty = Faculty::find($id);

        $faculty->update($request->all());

        return redirect("/facultades/{$id}");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $faculty = Faculty::find($id);

        $faculty->delete();

        return redirect("/facultades"); 
    }
}

resources/views/faculties/faculty.blade.php
<!-- vista principal de facultades, incluida desde la public function index en el controllador facultiesController-->

@extends('layouts/layout')

@section('title', 'Facultades') <!-- titulo de la de la pestaña -->

@section('content')

	<!-- formulario para crear nuevas facultades. Los datos se envían a la misma ruta y los toma la public function store del controllador (facultiesController) para crear nuevos registros en la tabla faculties-->

<div class="container">	
	<br>
	<h3>Crear facultades</h3>
	<form method="post" action= " {{route('facultades.store')}}">
		{{csrf_field()}}
		<div class="mb-3">
		    <input type="text" class="form-control"  name="name" placeholder ="Nombre..." required autofocus>
		</div>
		<div class="mb-3">
		    <label for="description"  class="form-label" >Descripción</label>
		    <textarea class="form-control" id="description" name="description"></textarea> 
	    </div>
		<button type="submit" class="btn btn-primary" name="send">Crear</button>
	</form>
</div>

<br>
	
<!-- este foreach muestra los datos de la tabla faculties--> 	
<div class="container">
	<table class="table table-striped table-responsive" >
	  <thead class="thead-dark">
	    <tr >
	      <th scope="col">Nombre</th>
	      <th scope="col">Descripción</th>
	    </tr>
	  </thead>	
	  <tbody>
		@foreach ($faculties as $faculty)
		<tr>
	      <td><a class="link-light" href="{{route('facultades.show', $faculty->id)}}">{{$faculty->name}}</a></td>
	      <td>{{$faculty->description}}</td>
	    </tr>
		@endforeach
  </tbody>
</table>
	
@endsection

resources/views/faculties/show.blade.php
@extends('..layouts/layout')

@section('title', 'Modificar facultades') <!-- titulo de la de la pestaña -->

@section('content')


<div class="container justify-content-md-center">	
	<br>

	<!-- Vista de la facultad -->
	<div >
		<h1>{{$faculty->name}}</h1>
		<p class="text-justify"> {{$faculty->description}} </p>
		<form method="post" action= "{{route('facultades.destroy', $faculty->id)}}" >
			{{csrf_field()}}
			<input type="hidden" name="_method" value="DELETE">
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Editar</button>
			<button class="btn btn-secondary"  type="submit" name="send" value="Eliminar" >Eliminar</button>
		</form>
	</div>

	<br>

	<!-- Modal -->
	<div class="modal fade" id="myModal" role="dialog">
		<div class="modal-dialog">


			<div class="modal-content">
				<div class="modal-header">

					<h4 class="modal-title">Editar</h4>
				</div>
				<div class="modal-body">
					<div >
						<!-- formulario para enviar datos actualizados de una facultad ya existente. Los datos se envían a la misma ruta y los toma la public function edit del controllador (facultiesController), para actualizar  registros en la tabla faculties-->
						<form method="post" action= "{{route('facultades.update', $faculty->id)}}">
							{{csrf_field()}}
							<input type="hidden" name="_method" value="PUT">
							<div class="mb-3"> 
								<input type="text" class="form-control"  name="name" value="{{$faculty->name}}" required autofocus>
							</div>
							<div class="mb-3"> 
								<textarea class="form-control" id="description" name="description" ></textarea> 
							</div>
							<button type="submit" class="btn btn-primary" name="send">Aceptar</button>
						</form>

					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>

		</div>
	</div>


	<h3>Programas vinculados</h3>
	<ul class="list-group list-group-flush">

		<!-- comprueba si el array  esta vacio-->
		@if($programs == '[]')
		<br>
		<p>No hay programas vinculados a esta facultad <a href="{{route('programas.index')}}/" class="link-light">ir</p> 
		@else
		@foreach($programs as $program)

		<li class="list-group-item"><a href="{{route('programas.show', $program->id)}}/" class="link-light">{{$program->name}}</a></li>

		@endforeach
		@endif 

	</ul> 
	<br>
</div>


@endsection